/**
 * @file st_sys_clock.h
 * @brief Clock specfics for the stml4.
 * @author TJ Malaska
 * @date
 */

#pragma once

#include "stm32l476xx.h"
#include "stm32l4xx_hal.h"
#include "sys_clock.h"

namespace LBR::Stml4
{

class HwClock : public Clock
{
public:
    enum class configuration
    {
        DEFAULT_4MHZ,
        HSI_80MHZ,
        HSI_64MHZ,
        HSE_64MHZ, /* NOTE won't work on nucleos unless resistors are changed, see datasheet. */
    };

    /**
     * @brief Initialize the system clock at the begining of the program in bsp ONCE. 
     *  this should be called BEFORE any other periopheral are setup.
     * @param Configuration to be used.
     * @return True if success.
     */
    bool init(configuration);

    uint32_t get_hz() const
    {
        return hz;
    }
    uint32_t get_timingR() const
    {
        return i2c_const;
    }

private:
    /* Will hold MAGIC numbers for I2c generated by cubeMX */
    uint32_t i2c_const;
    uint32_t hz;
};

}  // namespace LBR::Stml4